packages:
  - apps/*

onlyBuiltDependencies:
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - blake-hash
  - esbuild
  - near-sandbox
  - near-workspaces
  - secp256k1
  - sharp
  - unrs-resolver
  - yarn
